services:
  postgres:
    image: postgres:latest
    container_name: sully-postgres
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
